### ISSUE TITLE
About the construction of supervised datasets

### ISSUE THREAD

**Issue by houliping** [karthickai/trappm#1]
Thank you for your contribution, now I would like to use this method to train more model structures, may I ask the author, how the supervised dataset in .gexf.pt format is generated, can you provide some reference code? I would be grateful for your reply.

**Comment by karthickai** [comment]
Thank you for your interest in our work. I wanted to let you know that I have updated the TraPPM repo with a reference data collection script. Please adapt it to your dataset for metrics collection. 
https://github.com/karthickai/trappm/tree/master/dataset
